{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "3c714128",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-08-14 12:55:47.358153: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
      "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "E0000 00:00:1755168947.376860   11514 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
      "E0000 00:00:1755168947.382467   11514 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "2025-08-14 12:55:49,693 [WARNING] Please first ``pip install -U qiskit`` to enable related functionality in translation module\n"
     ]
    }
   ],
   "source": [
    "from utiles import *\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "c145cd82",
   "metadata": {},
   "outputs": [],
   "source": [
    "noise_list = np.array([1e-3]+list(np.logspace(-2.,-0.2,10))+[0.8,0.9])\n",
    "args = {\n",
    "    \"model_type\": [\"QNN\"],\n",
    "    \"learning_rate\": [0.001],  # will be converted to strings internally\n",
    "    \"batch_size\": [50],\n",
    "    \"num_features\": [4],\n",
    "    \"init_std\": [1],\n",
    "    \"init_std_Q\": [1],\n",
    "    \"layer_depth\": [1],\n",
    "    \"num_frequencies\": [5],\n",
    "    \"weight_decay\": [0],\n",
    "    \"ad\":[0],\n",
    "    \"pd\":noise_list,\n",
    "    \"dp\":[0],\n",
    "    \"noise_std\": [0.05]\n",
    "}\n",
    "\n",
    "futures = parallel_experiments(\n",
    "    args,                    # args is a dictionary with keys:\n",
    "                             # \"model_type\", \"learning_rate\", \"batch_size\", \"num_features\",\n",
    "                             # \"init_std\", \"layer_depth\", \"num_frequencies\", \"weight_decay\", \"bond_dim\"\n",
    "    target_epochs = 10000,           # number of training epochs (scalar)\n",
    "    n_trajectories = 10,          # number of trajectories (ind_trajectory values)\n",
    "    db_path = \"sqlite:///simulation_results.db\",                 # MLflow database URI, e.g. \"sqlite:///experiments.db\"\n",
    "#     db_path = \"mysql+mysqlconnector://slava:3dnvbeu82$@172.21.0.2/mlflow_db\",\n",
    "#     db_path = \"mysql+mysqlconnector://slava:3dnvbeu82%24@172.21.0.2:3306/mlflow_db\",\n",
    "    prune_callback = None,          # optional Optuna prune callback or None\n",
    "    print_output = False,            # Boolean flag\n",
    "    use_mlflow = True,              # Boolean flag for MLflow usage\n",
    "    smoothing = 0,               # smoothing for classification loss (scalar)\n",
    "    test_size = 0,               # fraction of data to reserve for test split (if needed)\n",
    "    val_size = 0.095,                # fraction of data to reserve for validation split\n",
    "    experiment_name=\"noisy_regularisation_171\",         # MLflow experiment name (string)\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d441d66c",
   "metadata": {},
   "outputs": [],
   "source": [
    "!rm -f simulation_results.db"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "a77d96dd",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2025/08/14 13:11:23 INFO mlflow.store.db.utils: Updating database tables\r\n",
      "INFO  [alembic.runtime.migration] Context impl SQLiteImpl.\r\n",
      "INFO  [alembic.runtime.migration] Will assume non-transactional DDL.\r\n",
      "INFO  [alembic.runtime.migration] Running upgrade  -> 451aebb31d03, add metric step\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py\", line 1964, in _exec_single_context\r\n",
      "    self.dialect.do_execute(\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py\", line 945, in do_execute\r\n",
      "    cursor.execute(statement, parameters)\r\n",
      "sqlite3.OperationalError: no such table: metrics\r\n",
      "\r\n",
      "The above exception was the direct cause of the following exception:\r\n",
      "\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/usr/local/bin/mlflow\", line 8, in <module>\r\n",
      "    sys.exit(cli())\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/click/core.py\", line 1161, in __call__\r\n",
      "    return self.main(*args, **kwargs)\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/click/core.py\", line 1082, in main\r\n",
      "    rv = self.invoke(ctx)\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/click/core.py\", line 1697, in invoke\r\n",
      "    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/click/core.py\", line 1697, in invoke\r\n",
      "    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/click/core.py\", line 1443, in invoke\r\n",
      "    return ctx.invoke(self.callback, **ctx.params)\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/click/core.py\", line 788, in invoke\r\n",
      "    return __callback(*args, **kwargs)\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/mlflow/db.py\", line 27, in upgrade\r\n",
      "    mlflow.store.db.utils._upgrade_db(engine)\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/mlflow/store/db/utils.py\", line 223, in _upgrade_db\r\n",
      "    command.upgrade(config, \"heads\")\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/alembic/command.py\", line 408, in upgrade\r\n",
      "    script.run_env()\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/alembic/script/base.py\", line 586, in run_env\r\n",
      "    util.load_python_file(self.dir, \"env.py\")\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py\", line 95, in load_python_file\r\n",
      "    module = load_module_py(module_id, path)\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py\", line 113, in load_module_py\r\n",
      "    spec.loader.exec_module(module)  # type: ignore\r\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 883, in exec_module\r\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/mlflow/store/db_migrations/env.py\", line 84, in <module>\r\n",
      "    run_migrations_online()\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/mlflow/store/db_migrations/env.py\", line 78, in run_migrations_online\r\n",
      "    context.run_migrations()\r\n",
      "  File \"<string>\", line 8, in run_migrations\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/alembic/runtime/environment.py\", line 946, in run_migrations\r\n",
      "    self.get_context().run_migrations(**kw)\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/alembic/runtime/migration.py\", line 623, in run_migrations\r\n",
      "    step.migration_fn(**kw)\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/mlflow/store/db_migrations/versions/451aebb31d03_add_metric_step.py\", line 20, in upgrade\r\n",
      "    op.add_column(\"metrics\", sa.Column(\"step\", sa.BigInteger(), nullable=False, server_default=\"0\"))\r\n",
      "  File \"<string>\", line 8, in add_column\r\n",
      "  File \"<string>\", line 3, in add_column\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/alembic/operations/ops.py\", line 2157, in add_column\r\n",
      "    return operations.invoke(op)\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/alembic/operations/base.py\", line 441, in invoke\r\n",
      "    return fn(self, operation)\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/alembic/operations/toimpl.py\", line 170, in add_column\r\n",
      "    operations.impl.add_column(table_name, column, schema=schema, **kw)\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/alembic/ddl/impl.py\", line 373, in add_column\r\n",
      "    self._exec(base.AddColumn(table_name, column, schema=schema))\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/alembic/ddl/impl.py\", line 246, in _exec\r\n",
      "    return conn.execute(construct, params)\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py\", line 1416, in execute\r\n",
      "    return meth(\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/ddl.py\", line 187, in _execute_on_connection\r\n",
      "    return connection._execute_ddl(\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py\", line 1527, in _execute_ddl\r\n",
      "    ret = self._execute_context(\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py\", line 1843, in _execute_context\r\n",
      "    return self._exec_single_context(\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py\", line 1983, in _exec_single_context\r\n",
      "    self._handle_dbapi_exception(\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py\", line 2352, in _handle_dbapi_exception\r\n",
      "    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/base.py\", line 1964, in _exec_single_context\r\n",
      "    self.dialect.do_execute(\r\n",
      "  File \"/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py\", line 945, in do_execute\r\n",
      "    cursor.execute(statement, parameters)\r\n",
      "sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: metrics\r\n",
      "[SQL: ALTER TABLE metrics ADD COLUMN step BIGINT DEFAULT '0' NOT NULL]\r\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\r\n"
     ]
    }
   ],
   "source": [
    "!mlflow db upgrade sqlite:///simulation_results.db"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "de810479",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[1;32m[+] Installing basic tools...\u001b[0m\n",
      "Get:1 file:/var/cuda-repo-ubuntu2204-12-4-local  InRelease [1572 B]\n",
      "Hit:2 http://10.101.101.120:5000 jammy InRelease\n",
      "Get:1 file:/var/cuda-repo-ubuntu2204-12-4-local  InRelease [1572 B]            \n",
      "Get:3 file:/var/cuda-repo-ubuntu2204-12-5-local  InRelease [1572 B]            \n",
      "Get:3 file:/var/cuda-repo-ubuntu2204-12-5-local  InRelease [1572 B]            \n",
      "Hit:4 https://download.docker.com/linux/ubuntu jammy InRelease                 \n",
      "Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease                         \n",
      "Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease                 \n",
      "Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease               \n",
      "Hit:8 http://security.ubuntu.com/ubuntu jammy-security InRelease               \n",
      "Hit:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease\n",
      "Reading package lists... Done\n",
      "W: http://10.101.101.120:5000/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.\n",
      "W: Conflicting distribution: http://10.101.101.120:5000 jammy InRelease (expected jammy but got focal)\n",
      "Reading package lists... Done\n",
      "Building dependency tree... Done\n",
      "Reading state information... Done\n",
      "lsb-release is already the newest version (11.1.0ubuntu4).\n",
      "ca-certificates is already the newest version (20240203~22.04.1).\n",
      "curl is already the newest version (7.81.0-1ubuntu1.20).\n",
      "gnupg is already the newest version (2.2.27-3ubuntu2.4).\n",
      "apt-transport-https is already the newest version (2.4.14).\n",
      "The following package was automatically installed and is no longer required:\n",
      "  nsight-compute-2024.2.0\n",
      "Use 'apt autoremove' to remove it.\n",
      "0 upgraded, 0 newly installed, 0 to remove and 165 not upgraded.\n",
      "\u001b[1;32m[+] Docker CLI already present.\u001b[0m\n",
      "\u001b[1;32m[+] Starting docker with systemd...\u001b[0m\n",
      "Synchronizing state of docker.service with SysV service script with /lib/systemd/systemd-sysv-install.\n",
      "Executing: /lib/systemd/systemd-sysv-install enable docker\n",
      "System has not been booted with systemd as init system (PID 1). Can't operate.\n",
      "Failed to connect to bus: Host is down\n"
     ]
    }
   ],
   "source": [
    "!./setup_mlflow_mysql.sh\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "b9c4ebe5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "unable to get image 'mysql:8.0': Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\r\n"
     ]
    }
   ],
   "source": [
    "!docker compose up -d"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "386ad04b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/bin/bash: line 1: initdb: command not found\r\n"
     ]
    }
   ],
   "source": [
    "!initdb -D /root/jupyter/tutorial/VK_Folder/Noisy_regularisation/pgdata"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "138ad67e",
   "metadata": {},
   "outputs": [
    {
     "ename": "Exception",
     "evalue": "<class 'sqlalchemy.exc.OperationalError'>(['(sqlite3.OperationalError) duplicate column name: step'])",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mException\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[5], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mfutures\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m0\u001b[39;49m\u001b[43m]\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/home/venvs/jax-gpu/lib/python3.10/site-packages/celery/result.py:251\u001b[0m, in \u001b[0;36mAsyncResult.get\u001b[0;34m(self, timeout, propagate, interval, no_ack, follow_parents, callback, on_message, on_interval, disable_sync_subtasks, EXCEPTION_STATES, PROPAGATE_STATES)\u001b[0m\n\u001b[1;32m    248\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mresult\n\u001b[1;32m    250\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mbackend\u001b[38;5;241m.\u001b[39madd_pending_result(\u001b[38;5;28mself\u001b[39m)\n\u001b[0;32m--> 251\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mbackend\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwait_for_pending\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    252\u001b[0m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    253\u001b[0m \u001b[43m    \u001b[49m\u001b[43minterval\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43minterval\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    254\u001b[0m \u001b[43m    \u001b[49m\u001b[43mon_interval\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m_on_interval\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    255\u001b[0m \u001b[43m    \u001b[49m\u001b[43mno_ack\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mno_ack\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    256\u001b[0m \u001b[43m    \u001b[49m\u001b[43mpropagate\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mpropagate\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    257\u001b[0m \u001b[43m    \u001b[49m\u001b[43mcallback\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcallback\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    258\u001b[0m \u001b[43m    \u001b[49m\u001b[43mon_message\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mon_message\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    259\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/home/venvs/jax-gpu/lib/python3.10/site-packages/celery/backends/asynchronous.py:223\u001b[0m, in \u001b[0;36mAsyncBackendMixin.wait_for_pending\u001b[0;34m(self, result, callback, propagate, **kwargs)\u001b[0m\n\u001b[1;32m    221\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m _ \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_wait_for_pending(result, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m    222\u001b[0m     \u001b[38;5;28;01mpass\u001b[39;00m\n\u001b[0;32m--> 223\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mresult\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmaybe_throw\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcallback\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcallback\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mpropagate\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mpropagate\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/home/venvs/jax-gpu/lib/python3.10/site-packages/celery/result.py:365\u001b[0m, in \u001b[0;36mAsyncResult.maybe_throw\u001b[0;34m(self, propagate, callback)\u001b[0m\n\u001b[1;32m    362\u001b[0m state, value, tb \u001b[38;5;241m=\u001b[39m (\n\u001b[1;32m    363\u001b[0m     cache[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mstatus\u001b[39m\u001b[38;5;124m'\u001b[39m], cache[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mresult\u001b[39m\u001b[38;5;124m'\u001b[39m], cache\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtraceback\u001b[39m\u001b[38;5;124m'\u001b[39m))\n\u001b[1;32m    364\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m state \u001b[38;5;129;01min\u001b[39;00m states\u001b[38;5;241m.\u001b[39mPROPAGATE_STATES \u001b[38;5;129;01mand\u001b[39;00m propagate:\n\u001b[0;32m--> 365\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mthrow\u001b[49m\u001b[43m(\u001b[49m\u001b[43mvalue\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_to_remote_traceback\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtb\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    366\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m callback \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m    367\u001b[0m     callback(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mid, value)\n",
      "File \u001b[0;32m/home/venvs/jax-gpu/lib/python3.10/site-packages/celery/result.py:358\u001b[0m, in \u001b[0;36mAsyncResult.throw\u001b[0;34m(self, *args, **kwargs)\u001b[0m\n\u001b[1;32m    357\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mthrow\u001b[39m(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[0;32m--> 358\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mon_ready\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mthrow\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/home/venvs/jax-gpu/lib/python3.10/site-packages/vine/promises.py:235\u001b[0m, in \u001b[0;36mpromise.throw\u001b[0;34m(self, exc, tb, propagate)\u001b[0m\n\u001b[1;32m    233\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m tb \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mand\u001b[39;00m (exc \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;129;01mor\u001b[39;00m exc \u001b[38;5;129;01mis\u001b[39;00m current_exc):\n\u001b[1;32m    234\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m\n\u001b[0;32m--> 235\u001b[0m \u001b[43mreraise\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mtype\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mexc\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mexc\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtb\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m/home/venvs/jax-gpu/lib/python3.10/site-packages/vine/utils.py:27\u001b[0m, in \u001b[0;36mreraise\u001b[0;34m(tp, value, tb)\u001b[0m\n\u001b[1;32m     25\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m value\u001b[38;5;241m.\u001b[39m__traceback__ \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m tb:\n\u001b[1;32m     26\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m value\u001b[38;5;241m.\u001b[39mwith_traceback(tb)\n\u001b[0;32m---> 27\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m value\n",
      "\u001b[0;31mException\u001b[0m: <class 'sqlalchemy.exc.OperationalError'>(['(sqlite3.OperationalError) duplicate column name: step'])"
     ]
    }
   ],
   "source": [
    "futures[0].get()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "jax-gpu",
   "language": "python",
   "name": "jax-gpu"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
